# Generated by Django 5.0.2 on 2024-09-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_register_table',
            name='account_number',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer_register_table',
            name='registered_datetime',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
