# Generated by Django 5.0.2 on 2024-10-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0003_rename_registered_datetime_customer_register_table_registered_dt'),
    ]

    operations = [
        migrations.CreateModel(
            name='bank_statment_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=100)),
                ('deposit_number', models.CharField(max_length=100)),
                ('withdraw_amount', models.CharField(max_length=100)),
                ('registered_dt', models.CharField(max_length=100)),
                ('balance_amount', models.CharField(max_length=100)),
            ],
        ),
    ]
